### ISSUE TITLE
Nuxt.js Database connection

### ISSUE THREAD

**Issue by onsombal** [lyquocnam/feathersjs-nuxt#1]
Hello, I really like your project. I'm not writing you about any specific issue. Rather, I wish to pick your brain about interfacing your project to a database that is managed by Feathers.js.

Your project has helped me better understand the interplay between Feathers.js and Nuxt.js for processing views. However, I'm struggling learning how to pass Vuex Store data to Feathers.js. Currently, I'm using Nedb for my database, but I'm not having any success using either Nuxt.js Classical or Modules modes.

I welcome any direction or hints you might be willing to share about best practices for passing Nuxt.js client gathered data to Feathers.js on the server side.

Thank you.

Regards... Jim

**Comment by lyquocnam** [comment]
we can use api @onsombal and get `axios` get data from server.
you can see in nuxt document. https://nuxtjs.org/guide/async-data

**Comment by kieusonlam** [comment]
Hi @onsombal you can use `axios` like @lyquocnam said or you also can use `feathers-client`

For example we gonna make a file to use feathers-client name it `feathers.js` or whatever you want
```
import io from 'socket.io-client';
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import socketio from 'feathers-socketio/client';
import authentication from 'feathers-authentication-client';

const storage = (process.BROWSER_BUILD) ? window.localStorage : null;

const socket = io('http://localhost:3030');
const client = feathers();

client.configure(hooks());
client.configure(socketio(socket));
client.configure(authentication({
    storage
}));

export default client;
```
in you store just import and using it
```
import client from '../feathers';

export default {
  state: {
    total: 0,
    limit: 5,
    skip: 0,
    data: [],
    currentPage: 1,
    single: null
  },

  actions: {
    async nuxtServerInit ({ dispatch }, { req }) {
        await dispatch('FETCH_ARTICLES', { page: 1 });
    },
    FETCH_ARTICLES: ({ commit, state }, { page = 1, sort }) => {
        commit('SET_CURRENT_PAGE', page)
        const skipPage = state.limit * (page - 1);
        let sortQuery =  { createdAt: -1 };
        if (sort) {
            sortQuery = { 
                [sort.field]: sort.order 
            }
        }
        return client.service('api/articles').find({
            query: {
                $limit: state.limit,
                $sort: sortQuery,
                $skip: skipPage
            }
        }).then(response => {
            commit('SET_ARTICLES', { response })
        })
   },

  mutations: {
    SET_ARTICLES: (state, { response }) => {
        state.total = response.total
        state.limit = response.limit
        state.skip = response.skip
        state.data = response.data
    },

  },

  getters: {

  }
}
```
if you using feathers-cli you might have some issues about nuxt and feathers using same route. So I prefer you edit your route after generate, that why you saw I use feathers-client like this `client.service('api/articles')` in the above code.

**Comment by onsombal** [comment]
@lyquocnam -- thank you for your quick reply. I'll let you know how well I progress on your suggestion for using axios with Nuxt.js async data. Again, I truly appreciate your sharing the boilerplate for a feathers-nuxt website app.

@kieusonlam -- I wish to also thank you for your quick reply. My goal now is to create solutions based on both your recommendation for using feathers-client and @lyquocnam's suggestion for using axious. I do have one question about the example code you provided. My implementation of @lyquocnam's website app is to enable users to make posts similar to Hacker News. My posts app will be synchronous rather than asynchronous. Thus, I'm assuming I will use import REST rather than socket.io.

I'm only a week into learning both feathersjs and nuxt.js along with gaining a basic understanding of vue.js and vuex support by nuxt.js. So, it might take me a while to get each of your suggestions working with @lyquocnam's FeathersJS + NuxtJS (VueSSR) website app. The good news is @lyquocnam's website app is helping me accelerate my learning process.

Regards... Jim
